version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    assignees:
      - markwhitaker
  - package-ecosystem: npm
    directory: /SaturdayQuizWeb.JavaScriptTests
    schedule:
      interval: weekly
    assignees:
      - markwhitaker
