version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    assignees:
      - markwhitaker
    groups:
      minor-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
  - package-ecosystem: npm
    directory: /SaturdayQuizWeb.JavaScriptTests
    schedule:
      interval: weekly
    assignees:
      - markwhitaker
    groups:
      minor-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
