aliases:
  - &setup-environment
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

version: 2

jobs:
  build:
    <<: *setup-environment
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build library
          command:
            dotnet build
      - run:
          name: Run unit tests
          command:
            dotnet test SaturdayQuizWeb.UnitTests
      - run:
          name: Run integration tests
          command:
            dotnet test SaturdayQuizWeb.IntegrationTests
