version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
#          filters:
#            branches:
#              only: main

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build library
          command:
            dotnet build
      - run:
          name: Run tests
          command:
            dotnet test SaturdayQuizWeb.UnitTests
