aliases:
  - &setup-environment
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

version: 2

jobs:
  build:
    <<: *setup-environment
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build library
          command:
            dotnet build
      - run:
          name: Run tests
          command:
            dotnet test
