name: Deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test main
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          dotnet-quality: ga
      - name: Build release build
        run: dotnet build -c Release
      - name: Test release build
        run: dotnet test -c Release SaturdayQuizWeb.UnitTests

  deploy-to-heroku:
    name: Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fiendish-eaton
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
        env:
          # See https://github.com/jincod/dotnetcore-buildpack/issues/131#issuecomment-726409101
          # and https://github.com/AkhileshNS/heroku-deploy#environment-variables
          HD_DOTNET_SDK_VERSION: 7.0.100
          HD_DOTNET_RUNTIME_VERSION: 7.0.0
