name: Deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test main
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          dotnet-quality: ga
      - name: Build (release)
        run: dotnet build -c Release
      - name: Run unit tests (release)
        run: dotnet test -c Release SaturdayQuizWeb.UnitTests

  run-integration-tests:
    name: Run integration tests
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          dotnet-quality: ga
      - name: Build (release)
        run: dotnet build -c Release
      - name: Run integration tests (release)
        run: dotnet test -c Release SaturdayQuizWeb.IntegrationTests

  deploy-to-heroku:
    name: Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fiendish-eaton
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
