name: Build and test branch
on:
  push:
    branches:
      - "!main"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test-branch:
    name: Build and test branch
    uses: ./.github/workflows/build-and-test.yml
