name: build-and-test-branch
on:
  push:
    branches:
      - "!main"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
