name: Auto-merge Dependabot PR (minor)
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: markwhitaker/shared-workflows/.github/workflows/dependabot-auto-merge-minor.yml@main
    with:
      pr-number: ${{ github.event.pull_request.number }}
